apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ai
  template:
    metadata:
      labels:
        app: frontend-ai
    spec:
      containers:
        - name: ai-frontend
          image: devacraifuture.azurecr.io/frontend:e1ed44b190871e270f93567bb91fc116d0a6aab3
          imagePullPolicy: Always
          ports:
            - containerPort: 80