apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ai
  template:
    metadata:
      labels:
        app: frontend-ai
    spec:
      containers:
        - name: ai-frontend
          image: devacraifuture.azurecr.io/frontend:cf8a5e677e26474b861c25083b38fbf1f1afd40f
          imagePullPolicy: Always
          ports:
            - containerPort: 80