apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ai
  template:
    metadata:
      labels:
        app: frontend-ai
    spec:
      containers:
        - name: ai-frontend
          image: devacraifuture.azurecr.io/frontend:4017d90da60ba39975e610a907446b15977e2766
          imagePullPolicy: Always
          ports:
            - containerPort: 80