apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-get-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-get-ai
  template:
    metadata:
      labels:
        app: backend-get-ai
    spec:
      containers:
        - name: backend-get-ai
          image: devacraifuture.azurecr.io/backend_get:e9fb3969f54f4a41e91a5a24579dda5c0e2ada10
          imagePullPolicy: Always
          ports: 
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: sql-connection-secret
          env:
            - name: SERVICE_NAME
              value: "tasks"