apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-get-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-get-ai
  template:
    metadata:
      labels:
        app: backend-get-ai
    spec:
      containers:
        - name: backend-get-ai
          image: devacrai11.azurecr.io/backend_get:5a3d744a161eb952413b3009f3616d8fd5ce6797
          imagePullPolicy: Always
          ports: 
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: sql-conn-secret
          env:
            - name: SERVICE_NAME
              value: "tasks"