apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-get-ingress
  annotations:
    kubernetes.io/ingress.class: "azure-application-gateway"
spec:
  ingressClassName: "azure-application-gateway"
  rules:
    - host: neuralixget.apforge.info   # replace with your get-task FQDN
      http:
        paths:
          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: backend-get-svc-ai   # ensure this Service exists / name matches
                port:
                  number: 9030