apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-get-ingress
  annotations:
    kubernetes.io/ingress.class: "azure-application-gateway"
    appgw.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "azure-application-gateway"
  rules:
    - host: neuralix.apforge.info
      http:
        paths:
          - path: /api/get(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-get-svc-ai
                port:
                  number: 9030
