apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ai
  template:
    metadata:
      labels:
        app: frontend-ai
    spec:
      containers:
        - name: ai-frontend
          image: devacrai11.azurecr.io/frontend:a0eb6335ef556ab77f6c53e6e48fc7b597639ba3
          imagePullPolicy: Always
          ports:
            - containerPort: 80