apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ai
  template:
    metadata:
      labels:
        app: frontend-ai
    spec:
      containers:
        - name: ai-frontend
          image: devacrai11.azurecr.io/frontend:5154729d9a783f8ab44705a88885de9bb88a24f3
          imagePullPolicy: Always
          ports:
            - containerPort: 80