apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-add-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-add-ai
  template:
    metadata:
      labels:
        app: backend-add-ai
    spec:
      containers:
        - name: backend-add-ai
          image: devacrai11.azurecr.io/backend_add:5154729d9a783f8ab44705a88885de9bb88a24f3
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: sql-connection-secret
          env:
            - name: SERVICE_NAME
              value: "tasks"