apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-add-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-add-ai
  template:
    metadata:
      labels:
        app: backend-add-ai
    spec:
      containers:
        - name: backend-add-ai
          image: devacraifuture.azurecr.io/backend_add:00057d745dc8934f7aa2827e6e99c9e5b9389481
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: sql-connection-secret
          env:
            - name: SERVICE_NAME
              value: "tasks"