apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-add-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-add-ai
  template:
    metadata:
      labels:
        app: backend-add-ai
    spec:
      containers:
        - name: backend-add-ai
          image: devacrai11.azurecr.io/backend_add:470369509ba2b13941aef85ec086f036e6521519
          imagePullPolicy: Always
          ports:
            - containerPort: 5000