name: Build & Push Images

on:
  push:
    branches:
    - 'features/build'
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY_NAME: ${{ secrets.ACR_NAME }}
      FRONTEND_IMAGE: frontend
      BACKEND1_IMAGE: backend_add
      BACKEND2_IMAGE: backend_get
      ARM_USE_OIDC: "true"
      TAG: ${{ github.sha }}
      GET_API_BASE_URL: "http://104.40.59.187:9030"
      ADD_API_BASE_URL: "http://13.91.6.53:9020"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name $REGISTRY_NAME

      # ---------- FRONTEND ----------
      - name: Build and Push Frontend Image
        run: |
          docker build \
            --build-arg VITE_GET_API_BASE_URL=$GET_API_BASE_URL \
            --build-arg VITE_ADD_API_BASE_URL=$ADD_API_BASE_URL \
            -t $REGISTRY_NAME.azurecr.io/$FRONTEND_IMAGE:$TAG ./frontend

          docker push $REGISTRY_NAME.azurecr.io/$FRONTEND_IMAGE:$TAG


      # --------- BACKEND_1----------
      - name: Build and Push Backend_1 Image
        run: |
          docker build -t $REGISTRY_NAME.azurecr.io/$BACKEND1_IMAGE:$TAG ./backend/add-task
          docker push $REGISTRY_NAME.azurecr.io/$BACKEND1_IMAGE:$TAG

      # ---------- BACKEND_2 ----------
      - name: Build and Push Backend_2 Image
        run: |
          docker build -t $REGISTRY_NAME.azurecr.io/$BACKEND2_IMAGE:$TAG ./backend/get-task
          docker push $REGISTRY_NAME.azurecr.io/$BACKEND2_IMAGE:$TAG

      - name: Update image tags in manifests
        run: |
          set -x
          sed -i "s|image: ${REGISTRY_NAME}.azurecr.io/frontend:.*|image: ${REGISTRY_NAME}.azurecr.io/frontend:${TAG}|g" frontend/manifests/ui_development.yml
          sed -i "s|image: ${REGISTRY_NAME}.azurecr.io/backend_add:.*|image: ${REGISTRY_NAME}.azurecr.io/backend_add:${TAG}|g" backend/add-task/manifests/backend_add_deployment.yml
          sed -i "s|image: ${REGISTRY_NAME}.azurecr.io/backend_get:.*|image: ${REGISTRY_NAME}.azurecr.io/backend_get:${TAG}|g" backend/get-task/manifests/backend_get_deployment.yml
  
        
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Update image tag to $TAG [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
