apiVersion: v1
kind: Secret
metadata:
  name: mssql-conn-secret      # 👈 same name jo deployment mein use ho raha hai
  namespace: default           # agar ArgoCD kisi aur namespace mein deploy kare to woh daal
type: Opaque
stringData:
  DB_CONN_STRING: >-
    mssql+pyodbc://adminuser:Pamanu2friends)@devsqlserveraifuture.database.windows.net:1433/devsqlserveraifuture?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes&Connection+Timeout=30
